theme: minima

title: Title
author: Author
email: Email
description: >
  Description

show_excerpts: true # set to false to remove excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"
  skin: solarized-dark

header_pages:
  - about.md
  - portfolio.md
